### ISSUE TITLE
Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by day112** [oldfritter/goDCE#10]
![image](https://user-images.githubusercontent.com/10526728/69025576-90933400-0a02-11ea-9deb-88e9008429d1.png)

**Comment by oldfritter** [comment]
Please use "go get github.com/oldfritter/goDCE",
and you loss the "r".😄

**Comment by day112** [comment]
![image](https://user-images.githubusercontent.com/10526728/71359258-cb225a80-25c6-11ea-8503-3884e459557d.png)
文档修改一下

**Comment by oldfritter** [comment]
谢谢，没有发现这个
