### ISSUE TITLE
Match question

### ISSUE THREAD

**Issue by janiu-001** [oldfritter/goDCE#6]
From the project, Benefit a lot!  Would you help to answer a question?
For example we have UserA with OrderA and UserB with Ordre B, and the volume is the same

1. Matching finished, and push the amqp message to trade_executer, and wait to execute
2. UserA cancel the order
3. the UserA volume is zero, and will be failure when strike
4. In this case, OrderB is already removed from the order book, and it will never be matched.

Should i misunderstanding the logic, would you help to answer how the peatio handle this logic now?

**Comment by oldfritter** [comment]
Please [see this](https://github.com/oldfritter/goDCE/issues/7)
