### ISSUE TITLE
撮合的问题

### ISSUE THREAD

**Issue by janiu-001** [oldfritter/goDCE#7]
Hi，
想问一个关于撮合的问题，假设我们有用户A挂单OrderA，用户B挂单OrderB
1. 用户B提单后先到matching，然后到trading exchange，等待strike
2. 用户A取消订单
3. 先到matching，再到order processer，处理快，订单状态为0
4. 第一步开始执行，strike，这时候校验订单A，返回失败
5. 因为用户B的订单已经从order book移除，再没有机会撮合

**Comment by oldfritter** [comment]
你好，我们这里取消订单不是直接修改订单状态，事实上是由撮合引擎完成订单的取消，
撮合引擎中的订单移除后，才会修改数据库中的订单状态。
不会存在你预想的那种情况

**Comment by janiu-001** [comment]
你好，非常感谢你的回复，我重新去看了下你的代码，从新描述一下：
1. /api/:platform/v1/order/delete 接口调用V1PostOrderDelete 删除订单，把删除消息发到rabbitmq的Matching队列
2. submit 和cancel都在doMatching函数处理，然后分发到不同的协程处理
3. trade协程将match的订单发到TradeTreatExchange, cancel协程讲要取消的订单发送到OrderCancelExchange
4. 如果是cancel，在cancel的worker更新maindb,如果是submit再treat的worker进行trade记录保存，stike等操作
5. 所以这个取消和成交是两个独立的协程，回到我说的场景:

1. Ａ和Ｂ进行交易，在TradeTreatExchange排队进行最后的成交
2. 这时Ａ调用１中的接口取消交易，在OrderCancelExchange排队执行
3. 取消的任务执行快，Ａ的订单已经被取消，但是A和B还没有成交
4. 如果因为某些原因成交失败，或者校验Ａ的订单状态的时候失败，这个交易就会失败
5. 但是B已经从orderbook移除，再也没有去撮合的机会了

**Comment by oldfritter** [comment]
成交和撤单都是基于撮合引擎维护的一套红黑树，任何一个操作都是先修改红黑树里面的数据后在进行下一步的，所以总是先进入的操作被执行。如果已经撮合成交了，还没有完成订单以及成交记录入库的情况下，即使撤单了，撤单操作也是失败的。
