### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by janiu-001** [oldfritter/goDCE#8]
撮合结束之后，会成交，这地方会有大量的数据操作，这样会导致整体撮合的性能下降，这地方有优化的空间吗？

**Comment by oldfritter** [comment]
撮合成功后，仅向rabbitmq中发送一条消息，具体的业务是交给成交模块去处理，这个可以横向扩展。
与其担心系统的处理能力，不如关心数据库的性能瓶颈。
