### ISSUE TITLE
貌似没有 OTC 交易

### ISSUE THREAD

**Issue by af913337456** [oldfritter/goDCE#9]

**Comment by af913337456** [comment]
如题

**Comment by oldfritter** [comment]
这个就要根据自己的业务模型来开发了，主要由客服的业务流程来确定

**Comment by af913337456** [comment]
@oldfritter  目前你的开源中，只有一种功能，可以看作是币币交易。

**Comment by oldfritter** [comment]
@af913337456 
目前的情况，你开法币交易对，是法规不允许的。
如果你想开启，仅需要将发币作为一个币种引入即可。
